root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:promise/recommended
  - plugin:unicorn/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  import/prefer-default-export: warn
  import/no-default-export: off
  import/extensions:
    - warn
    - js: never
      ts: never
      jsx: never
      tsx: never
  unicorn/filename-case:
    - error
    - cases:
        camelCase: true
        pascalCase: true
  react/destructuring-assignment: off
  # react/jsx-filename-extension: off
  "@typescript-eslint/no-unused-expressions":
    - error
    - allowShortCircuit: true
      allowTernary: true
  react/prop-types:
    - off
overrides:
  - files:
      - "*.test.ts"
      - "*.test.tsx"
      - "*.test.js"
      - "*.test.jsx"
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
