env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
  - airbnb/hooks
  - plugin:promise/recommended
  - plugin:unicorn/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - promise
  - unicorn
rules:
  import/extensions:
    - warn
    - js: never
    - ts: never
    - jsx: never
    - tsx: never
