plugins:
  postcss-nested: {}
  postcss-preset-env:
    stage: 2
  autoprefixer: {}
# browsers:
#   - "> 1%"
#   - "last 2 versions"
#   - "ie >= 0"
#   - "ios >= 7"
#   - "android >= 4.4"

#  const postcssrc = require('postcss-load-config');

#  postcss plugins
#  const autoprefixer = require('autoprefixer');
#  const cssnano = require('cssnano');

#   postcss plugins options
#  const autoprefixerOptions = {
#    browsers: [
#      '> 1%',
#      'last 2 versions',
#      'ie >= 9',
#      'ios >= 7',
#      'android >= 4.4'
#    ]
#  };

#  const cssnanoOptions = {
#    preset: [
#      'default',
#      {
#        discardComments: {
#          removeAll: true
#        }
#      }
#    ]
#  };

#   postcss plugins
#  const cssnext = require('postcss-cssnext');
#  const cssnested = require('postcss-nested');
#  const cssimport = require('postcss-import');
