extends:
  - stylelint-config-standard
  - stylelint-config-prettier
customSyntax:
  - postcss-scss
# overrides:
#   - files:
#       - "**/*.tsx"
#       - "**/*.jsx"
#     customSyntax: "@stylelint/postcss-css-in-js"
rules:
  selector-class-pattern: ^[A-Z]?([a-z]\-?)+$
  keyframes-name-pattern: ^[A-Z]?([a-z]\-?)+$
